version: '3.8'

services:
  # --- MINIO: S3 object storage for Iceberg data and Hadoop catalog ---
  minio:
    image: bitnami/minio:2025.7.23
    container_name: minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Minio Web Console
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # --- ZOOKEEPER: Required for Kafka ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # --- KAFKA: Message broker for data streaming ---
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # --- FLINK: Stream processing engine ---
  flink-jobmanager:
    image: bitnami/flink:1.20.0
    container_name: flink-jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        s3.access-key: admin
        s3.secret-key: password
        s3.endpoint: http://minio:9000
        s3.path.style.access: "true"
    volumes:
      - ./flink-jars:/opt/flink/lib
    depends_on:
      - minio

  flink-taskmanager:
    image: bitnami/flink:1.20.0
    container_name: flink-taskmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 2
        s3.access-key: admin
        s3.secret-key: password
        s3.endpoint: http://minio:9000
        s3.path.style.access: "true"
    volumes:
      - ./flink-jars:/opt/flink/lib
    depends_on:
      - flink-jobmanager

  # --- DREMIO: Query engine ---
  dremio:
    image: bitnami/dremio:26.0.0
    container_name: dremio
    ports:
      - "9047:9047"   # Web UI
      - "31010:31010" # ODBC/JDBC
    volumes:
      - dremio-data:/opt/dremio/data
    depends_on:
      - minio

volumes:
  minio-data:
    external: true
  dremio-data:
    external: true